language: objective-c
osx_image: xcode7
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
install: 
  - carthage bootstrap --verbose
script: xctool -scheme BetaSeriesKit -sdk iphonesimulator test
